--liquibase formatted sql
--changeset svc_z_blog:tbl-category-001
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 SELECT COUNT(*) C FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='TBL_CATEGORY';
CREATE TABLE TBL_CATEGORY(
    `ID` INT NOT NULL,
    `NAME` NVARCHAR(500) NOT NULL,
    `SUMMARY` NVARCHAR(2000) NOT NULL,
    `CREATE_TIME` DATETIME DEFAULT NULL,
    `LAST_UPDATE` DATETIME DEFAULT NULL,

    PRIMARY KEY (`ID`),

    CONSTRAINT `POST_AUTHOR_FK`
        FOREIGN KEY (`AUTHOR`) REFERENCES TBL_USER (`ID`)
            ON DELETE CASCADE
            ON UPDATE RESTRICT
);
